name: Build-OpenWrt

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      WORK_PATH: /home/runner/work/build-openwrt/build-openwrt

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Build Environment Initialization
        run: |
          sudo apt-get update
          sudo apt-get -qq remove --purge mysql* php* google* firefox ghc azure-cli \
          dotnet* powershell ruby-full zulu* hhvm llvm*

          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /var/lib/docker
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache/go /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/node

          sudo curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh | sudo bash

          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean

      - name: Build Immortalwrt
        run: |
          chmod +x build.sh && ./build.sh

      - name: Package Build Env
        run: |
          tar -zcvf openwrt-env.tar.gz /home/runner/work/build-openwrt/build-openwrt/immortalwrt
          
      - name: Upload Build Env
        uses: actions/upload-artifact@v3
        with:
          name: Newifi3-d2-Env-${{ env.FILE_DATE }}
          path: /home/runner/work/build-openwrt/build-openwrt/openwrt-env.tar.gz
          
      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: Newifi3-d2-Packages-${{ env.FILE_DATE }}
          path: /home/runner/work/build-openwrt/build-openwrt/immortalwrt/bin/packages/

      - name: Upload Firmwares
        uses: actions/upload-artifact@v3
        with:
          name: Newifi3-d2-Firmwares-${{ env.FILE_DATE }}
          path: /home/runner/work/build-openwrt/build-openwrt/immortalwrt/bin/targets/

      - name: Upload bin
        uses: actions/upload-artifact@v3
        with:
          name: immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin-${{ env.FILE_DATE }}
          path: /home/runner/work/build-openwrt/build-openwrt/immortalwrt/bin/targets/ramips/mt7621/immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin

      - name: Upload manifest
        uses: actions/upload-artifact@v3
        with:
          name: manifest-${{ env.FILE_DATE }}
          path: /home/runner/work/build-openwrt/build-openwrt/immortalwrt/bin/targets/ramips/mt7621/immortalwrt-ramips-mt7621-d-team_newifi-d2.manifest
